apiVersion: v1
kind: ConfigMap
metadata:
  name: templatebot
data:
  # These configurations are injected as environment variables into the
  # templatebot app container.
  API_LSST_CODES_NAME: 'templatebot'
  API_LSST_CODES_PROFILE: "production"
  REGISTRY_URL: "http://localhost:8081"
  KAFKA_BROKER: "localhost:9092"
  KAFKA_PROTOCOL: "PLAINTEXT"
  # KAFKA_CLUSTER_CA: ""
  # KAFKA_CLIENT_CA: ""
  # KAFKA_CLIENT_CERT: ""
  # KAFKA_CLIENT_KEY: ""
  TEMPLATEBOT_SUBJECT_SUFFIX: ''
  TEMPLATEBOT_SUBJECT_COMPATIBILITY: 'FORWARD_TRANSITIVE'
  TEMPLATEBOT_SLACK_GROUP_ID: 'templatebot'
  TEMPLATEBOT_EVENTS_GROUP_ID: 'templatebot'
  TEMPLATEBOT_TOPIC_PRERENDER: 'templatebot.prerender'
  TEMPLATEBOT_TOPIC_RENDERREADY: 'templatebot.render-ready'
  TEMPLATEBOT_TOPIC_POSTRENDER: 'templatebot.postrender'
  SQRBOTJR_TOPIC_APP_MENTION: 'sqrbot.app.mention'
  SQRBOTJR_TOPIC_MESSAGE_IM: 'sqrbot.message.im'
  SQRBOTJR_TOPIC_INTERACTION: 'sqrbot.interaction'
  TEMPLATEBOT_REPO: "https://github.com/lsst/templates"
  TEMPLATEBOT_REPO_REF: "master"
  TEMPLATEBOT_ENABLE_SLACK_CONSUMER: "1"
  TEMPLATEBOT_ENABLE_EVENTS_CONSUMER: "1"
  TEMPLATEBOT_TOPIC_CONFIG: "1"
