sudo: required
dist: xenial
services:
  - docker
language: python
matrix:
  include:
    - python: "3.7.1"
      env: DEPLOY_DOCKER_IMAGE=true
install:
  - "make install"
script:
  - "make test"
  - "make image"
after_success:
  # Docker Hub (no-op for PRs and DEPLOY_DOCKER_IMAGE=false)
  - make travis-docker-deploy
env:
  global:
    - DEPLOY_DOCKER_IMAGE=false  # disable docker push in regular test matrix
    # DOCKER_USERNAME
    - secure: "kmDTrEuD5OZzEVr/G/KKtTunWvAVUH1bo1LzrdYCpKAa1ty/XctlOhmv52QB5v+ugyQtEG7601nb90zdmrRjPM6mGJh4PM65JuSFcc7y3DQuLO8KZakhuglIPw/M74iWviN35cIxNpUnoVeVJrWzdxHO9LLtop4t6ua+btS7ufgmDhrY7U0bnkNl8OwSELZ7rrmEA/Afr5sngIw/G8tGYSH/Q7WFiUxGusgbn0wG9CJ6lI0Ymu9RJ0WLrVzbcqbIj0DXtrnjk+IATYRgzLKqPg+aLmrsP/DF3L5HrsNsjSIgGNgAGKf26iNx01XDfi9tNglMl+Xytwzhc4kEa9VoSGxqYTrzi2cR4S4nlhRY09hJztR6teng5s0tH0JYRtoIBCAVKhPfQfSYvsuLTfDcJ1B2E8jZG1fWROOcLrKKe+7QoKWLb1ti8wK8EzC9q4NTzFX3TfUxXaSGVGTBCAxJ2OxidUnZLlqnAus8M0OZnHzvsJh8XOZasTYF4bxoi+NhikFCwIlP8mnypSFhehOjFCelPKET11X+Xu5GdB7SbwIgWyW0WWm7mG8DKvWpZY6Ky4z2nfOPcnmNOYdeS8CKFwgOYZt2jbYdc0FjtJxl+liiVbrrfO3V+EeNXYIcPoowVsXkMinoGUHfqmIMsbaWhunG+GYXN/ivZGubpJT6ahw="
    # DOCKER_PASSWORD
    - secure: "kMMA3Y7qy/q6Fdv7m2vYXoQGqIbZ4jkZetE+J2i+fUzMPjjPrpfP1ui1v5TimzXICtNtPU7TFy/q6GBPOhce2W2uLIwi8cfH7KDYDMiEJsTv++X93rn3B6EFV0kN3puQ5BrX8XarHpe7mbCbx8MVUnIUvJmG1g19W1EpE8UGpLM4CkI8+Ror+kyHmJxSa3x2jHhAqS0+Yr0I6J8PeqMUoPGpoOxgPHAvj5axsEDADel7bwlAbsS25P/jBhZcZU3gG2CGG3tvrvmJOiWN5kOnwl94bg2RK37YPD/jTc2XXAGtiuFr6A7CMgxrpHV1P1i5sVhucWG9ihannx/ieG2NkuNg6zb4fYuhOdZfbkpdU+RHvYNqpk8tKpikgquxlm88T7DpTqTxPAHha42SgRmsdsJEjk58evDNly5lzhBy+G68nmxT3/j+61k8A2FeEhU1+kmzj7Y9K4/y/K2NttmOCT5/wExXtye2Q93FCCiu6ycEObLZlESpAgU8GZNW9xv0kSDoau66PH1THyBBMHyNfusnZ3ZLe9A74nb2thB1dnpYL3RCg8pJ2wcAmrRvs4m32u9RrNf9bqvZoin/tKCE4+xARZhtjWNcVihxk5NG8KJbhVlllsvEKMTL7+4pZHPPihHp8sYMqM+mraKF+ivejchU1O8gN7EZC6A379Wd/Xs="
