# Credentials for templatebot app.
apiVersion: v1
kind: Secret
metadata:
  name: templatebot
type: Opaque
data:
  # echo -n '...' | base64
  TEMPLATEBOT_GITHUB_TOKEN: {{ TEMPLATEBOT_GITHUB_TOKEN }}
  TEMPLATEBOT_GITHUB_USER: {{ TEMPALTEBOT_GITHUB_USER }}
